PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX metric: <http://neontometrics.informatik.informatik.uni-rostock.de#>
SELECT DISTINCT ?itemName ?description ?definition ?interpretation ?implementedAs ?superClass ?seeAlso ?implementationName 
WHERE {

    {
        ?itemName rdfs:subClassOf* metric:Quality_Frameworks .
    }
    UNION
    {
        ?itemName rdfs:subClassOf* metric:Elemental_Metrics .
        BIND(1 as ?isElementalMetric)
    }
    
    OPTIONAL {?itemName rdfs:subClassOf ?superClass }
    OPTIONAL { ?itemName metric:MetricDescription ?description } .
    OPTIONAL { ?itemName metric:MetricDefinition ?definition } . 
    OPTIONAL { ?itemName rdfs:subClassOf _:v0 .
    _:v0 owl:onProperty metric:implementedBy ;
                    owl:hasValue ?implementationName }
    OPTIONAL { ?itemName metric:MetricInterpretation ?interpretation } .
    OPTIONAL { ?itemName rdfs:seeAlso ?seeAlso }
    
}
ORDER BY DESC(?isElementalMetric)