PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX metric: <http://neontometrics.informatik.informatik.uni-rostock.de#>
SELECT DISTINCT ?item ?description ?definition ?interpretation ?implementedAs ?superClass
WHERE {

    ?item rdfs:subClassOf* metric:Quality_Frameworks .
    
    OPTIONAL {?item rdfs:subClassOf ?superClass }
    OPTIONAL { ?item metric:MetricDescription ?description } .
    OPTIONAL { ?item metric:MetricDefinition ?definition } . 
    OPTIONAL { ?item metric:metricInterpretation ?interpretation } .
    OPTIONAL { ?item rdfs:seeAlso ?seeAlso } .
    
}