# Generated by Django 3.0.7 on 2020-09-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='orign',
            new_name='repository',
        ),
        migrations.RemoveField(
            model_name='source',
            name='time',
        ),
        migrations.AddField(
            model_name='metrics',
            name='author',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metrics',
            name='commitmessage',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metrics',
            name='committer',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metrics',
            name='time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='branch',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='fileName',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
