# Generated by Django 3.0.7 on 2020-09-22 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20200922_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metrics',
            name='author',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='commitmessage',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='committer',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='metrics',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='time',
            field=models.DateTimeField(default=None),
        ),
    ]
