# Generated by Django 3.1.1 on 2020-09-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_auto_20200922_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrics',
            name='metrics',
        ),
    ]
