# Generated by Django 3.1.1 on 2020-09-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_remove_metrics_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='CommitMessage',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='CommitTime',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='authorEmail',
            field=models.EmailField(blank=True, default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='authorName',
            field=models.TextField(blank=True, default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='commiterEmail',
            field=models.EmailField(blank=True, default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='committerName',
            field=models.TextField(blank=True, default=None, max_length=150),
        ),
    ]
