# Generated by Django 3.1.1 on 2020-09-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_auto_20200922_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='CommitMessage',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='CommitTime',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='authorEmail',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='authorName',
            field=models.TextField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='commiterEmail',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='committerName',
            field=models.TextField(default=None, max_length=150, null=True),
        ),
    ]
