# Generated by Django 3.1.1 on 2020-09-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_auto_20200922_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='DLexpressivity',
            field=models.CharField(blank=True, default=None, max_length=15),
        ),
    ]
