# Generated by Django 3.1.1 on 2020-09-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0010_auto_20200922_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='Negativeobjectpropertyassertionaxiomscount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
