# Generated by Django 3.1.1 on 2020-09-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0011_auto_20200922_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metrics',
            old_name='authorEmail',
            new_name='AuthorEmail',
        ),
        migrations.RenameField(
            model_name='metrics',
            old_name='authorName',
            new_name='AuthorName',
        ),
        migrations.RenameField(
            model_name='metrics',
            old_name='commiterEmail',
            new_name='CommiterEmail',
        ),
        migrations.RenameField(
            model_name='metrics',
            old_name='committerName',
            new_name='CommitterName',
        ),
        migrations.AlterField(
            model_name='metrics',
            name='Averagenumberofpaths',
            field=models.FloatField(default=0),
        ),
    ]
