# Generated by Django 3.1.1 on 2020-09-23 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0012_auto_20200922_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Classiri', models.CharField(default=None, max_length=400, null=True)),
                ('Classconnectivity', models.PositiveSmallIntegerField(default=0)),
                ('Classfulness', models.FloatField(default=0)),
                ('Classimportance', models.FloatField(default=0)),
                ('Classinheritancerichness', models.FloatField(default=0)),
                ('Classreadability', models.PositiveSmallIntegerField(default=0)),
                ('Classrelationshiprichness', models.PositiveSmallIntegerField(default=0)),
                ('Classchildrencount', models.PositiveSmallIntegerField(default=0)),
                ('Classinstancescount', models.PositiveSmallIntegerField(default=0)),
                ('Classpropertiescount', models.PositiveSmallIntegerField(default=0)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.metrics')),
            ],
        ),
    ]
