# Generated by Django 3.1.4 on 2021-03-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0013_classmetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='ReadingError',
            field=models.BooleanField(default=False),
        ),
    ]
