# Generated by Django 3.1.4 on 2021-03-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0014_metrics_readingerror'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='wholeRepoAnalyzed',
            field=models.BooleanField(default=False),
        ),
    ]
