# Generated by Django 3.1.4 on 2021-03-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0015_source_wholerepoanalyzed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='wholeRepoAnalyzed',
            new_name='wholeRepositoryAnalyzed',
        ),
    ]
