# Generated by Django 3.2.1 on 2021-05-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0016_auto_20210311_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='Absolutebreadth',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='Absolutedepth',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='Maximalbreadth',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='Maximaldepth',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
