# Generated by Django 3.2.1 on 2021-05-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0017_auto_20210521_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='Absoluteleafcardinality',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='Absoluterootcardinality',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='Absolutesiblingcardinality',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='Totalnumberofpaths',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
