# Generated by Django 3.2.1 on 2021-05-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0018_auto_20210521_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrics',
            name='Size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
