from django.db import models

# Create your models here.


class Source(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    repository = models.CharField(max_length=350)
    fileName = models.CharField(max_length=500)
    branch = models.CharField(max_length=150)
    wholeRepositoryAnalyzed = models.BooleanField(default=False)


class Metrics(models.Model):
    metricSource = models.ForeignKey(Source, on_delete=models.CASCADE)
    CommitTime = models.DateTimeField(default=None, null=True)
    CommitMessage = models.TextField(default=None, null=True)
    AuthorEmail = models.EmailField(default=None, null=True)
    AuthorName = models.TextField(max_length=150, default=None, null=True)
    CommiterEmail = models.EmailField(default=None, null=True)
    CommitterName = models.TextField(max_length=150, default=None, null=True)
    Size = models.PositiveIntegerField(default = 0)
    # metrics = models.TextField(default=None)
    ReadingError = models.TextField(default=False)
    absoluteBreadth = models.PositiveBigIntegerField(default=0)
    absoluteDepth = models.PositiveBigIntegerField(default=0)
    absoluteLeafCardinality = models.PositiveIntegerField(default=0)
    absoluteRootCardinality = models.PositiveIntegerField(default=0)
    absoluteSiblingCardinality = models.PositiveIntegerField(default=0)
    annotationAssertionsAxioms = models.PositiveBigIntegerField(default=0)
    annotationPropertyRangeaxioms = models.PositiveBigIntegerField(default=0)
    annotationPropertyDomainAxioms = models.PositiveBigIntegerField(default=0)
    anonymousClasses = models.PositiveBigIntegerField(default=0)
    asymmetricObjectPropertyAxioms = models.PositiveBigIntegerField(default=0)
    axioms = models.PositiveBigIntegerField(default=0)
    classAnnotations = models.PositiveBigIntegerField(default=0)
    classAssertionaxioms = models.PositiveBigIntegerField(default=0)
    classes = models.PositiveBigIntegerField(default=0)
    classesThatShareARelation = models.PositiveBigIntegerField(default=0)
    classesWithIndividuals = models.PositiveBigIntegerField(default=0)
    classesWithMoreThanOneAncestor = models.PositiveBigIntegerField(default=0)
    classesWithMultipleInheritance = models.PositiveBigIntegerField(default=0)
    classesWithObjectProperties = models.PositiveBigIntegerField(default=0)
    classesWithSubClassess = models.PositiveBigIntegerField(default=0)
    circleHierachies = models.SmallIntegerField(default=0)
    dataProperties = models.PositiveBigIntegerField(default=0)
    dataPropertyAnnotations = models.PositiveBigIntegerField(default=0)
    dataPropertyAssertionAxioms = models.PositiveBigIntegerField(default=0)
    dataPropertyDomainAxioms = models.PositiveBigIntegerField(default=0)
    dataPropertyRangeAxioms = models.PositiveBigIntegerField(default=0)
    datatypeAnnotations  = models.PositiveBigIntegerField(default=0)
    differentIndividualsAxioms  = models.PositiveBigIntegerField(default=0)
    disjointClassesAxioms  = models.PositiveBigIntegerField(default=0)
    disjointDataPropertiesAxioms  = models.PositiveBigIntegerField(default=0)
    disjointObjectPropertyAxioms  = models.PositiveBigIntegerField(default=0)
    DLExpressivity  = models.TextField(max_length=20, default=0)
    equivalentClassesAxioms  = models.PositiveBigIntegerField(default=0)
    equivalentDataPropertiesAxioms  = models.PositiveBigIntegerField(default=0)
    equivalentObjectPropertyAxioms  = models.PositiveBigIntegerField(default=0)
    functionalDataPropertyAxioms  = models.PositiveBigIntegerField(default=0)
    functionalObjectPropertyAxioms  = models.PositiveBigIntegerField(default=0)
    GCICount  = models.PositiveBigIntegerField(default=0)
    generalAnnotationAxioms  = models.PositiveBigIntegerField(default=0)
    HiddenGCICount  = models.PositiveBigIntegerField(default=0)
    individuals  = models.PositiveBigIntegerField(default=0)
    inverseFunctionalObjectPropertyAxioms  = models.PositiveBigIntegerField(default=0)
    inverseObjectPropertyAxioms  = models.PositiveBigIntegerField(default=0)
    inverseRelationsRatio  = models.PositiveBigIntegerField(default=0)
    individualAnnotation  = models.PositiveBigIntegerField(default=0)
    irreflexiveObjectPropertyAxioms  = models.PositiveBigIntegerField(default=0)
    irreflexiveObjectPropertyAxioms  = models.PositiveBigIntegerField(default=0)
    logicalAxioms  = models.PositiveBigIntegerField(default=0)
    maxFanoutnessOfLeafClasses  = models.PositiveBigIntegerField(default=0)
    maximalBreadth  = models.PositiveBigIntegerField(default=0)
    maximalDepth  = models.PositiveBigIntegerField(default=0)
    maxSubclassesOfAClass  = models.PositiveBigIntegerField(default=0)
    minimumBreath  = models.PositiveBigIntegerField(default=0)
    minimumDepth  = models.PositiveBigIntegerField(default=0)
    negativeDataPropertyAssertionAxioms  = models.PositiveBigIntegerField(default=0)
    negativeObjectPropertyAssertionAxioms  = models.PositiveBigIntegerField(default=0)
    numberOfConnectedGraphs  = models.PositiveBigIntegerField(default=0)
    objectProperties  = models.PositiveBigIntegerField(default=0)
    objectPropertiesOnClasses  = models.PositiveBigIntegerField(default=0)
    objectPropertiesOnClasses  = models.PositiveBigIntegerField(default=0)
    objectPropertyAssertionaxioms  = models.PositiveBigIntegerField(default=0)
    objectPropertyDomainAxioms  = models.PositiveBigIntegerField(default=0)
    objectPropertyRangeAxioms  = models.PositiveBigIntegerField(default=0)
    pathsToLeafClasses  = models.PositiveBigIntegerField(default=0)
    reflexiveObjectPropertyAxioms  = models.PositiveBigIntegerField(default=0)
    rootClasses  = models.PositiveBigIntegerField(default=0)
    sameIndividualsAxioms  = models.PositiveBigIntegerField(default=0)
    subDataPropertyOfAxioms  = models.PositiveBigIntegerField(default=0)
    subObjectPropertyOfAxioms  = models.PositiveBigIntegerField(default=0)
    subPropertyChainOfAxioms  = models.PositiveBigIntegerField(default=0)
    sumOfDirectAncestorClasses  = models.PositiveBigIntegerField(default=0)
    sumOfDirectAncestorOfLeafClasses  = models.PositiveBigIntegerField(default=0)
    sumOfDirectAncestorsWithMoreThanOneDirectAncestor  = models.PositiveBigIntegerField(default=0)
    superClasses  = models.PositiveBigIntegerField(default=0)
    superClassesOfClassesWithMultipleInheritance  = models.PositiveBigIntegerField(default=0)
    subClassOfAxioms  = models.PositiveBigIntegerField(default=0)
    subClassuperClassesOfLeafClassessOfAxioms  = models.PositiveBigIntegerField(default=0)
    symmetricObjectPropertyAxioms  = models.PositiveBigIntegerField(default=0)
    transitiveObjectPropertyAxioms  = models.PositiveBigIntegerField(default=0)
    superClassesOfLeafClasses  = models.PositiveBigIntegerField(default=0)
    objectPropertyAnnotations  = models.PositiveBigIntegerField(default=0)
  

class ClassMetrics(models.Model):
    metric = models.ForeignKey(Metrics, on_delete=models.CASCADE)
    Classiri = models.CharField(default = None, null=True, max_length=400)
    Classconnectivity = models.PositiveSmallIntegerField(default=0)
    Classfulness = models.FloatField(default = 0)
    Classimportance = models.FloatField(default = 0)
    Classinheritancerichness = models.FloatField(default = 0)
    Classreadability = models.PositiveSmallIntegerField(default = 0)
    Classrelationshiprichness = models.PositiveSmallIntegerField(default = 0)
    Classchildrencount = models.PositiveSmallIntegerField(default = 0)
    Classinstancescount = models.PositiveSmallIntegerField(default = 0)
    Classpropertiescount = models.PositiveSmallIntegerField(default = 0)